name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - run: pip install --upgrade pip
    - run: pip install "ruff<1" "black<24"
    - run: ruff check .
    - run: black --check .
